openapi: 3.1.0
info:
  title: Odin
  version: 1.0.0
  description: Сервис мониторинга здоровья проектов
  contact:
    name: API Support
    email: support@example.com
servers:
  - url: localhost:3000
paths:
  /communities:
    get:
      summary: Получить сообщества
      operationId: getCommunities
      tags:
        - Community
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Community'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Создать сообщество
      operationId: createCommunity
      tags:
        - Community
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommunity'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Community'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /communities/{id}:
    get:
      summary: Получить сообщество
      operationId: getCommunity
      tags:
        - Community
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Community'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Обновить сообщество
      operationId: updateCommunity
      tags:
        - Community
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommunity'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Community'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Удалить сообщество
      operationId: deleteCommunity
      tags:
        - Community
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /threads:
    get:
      summary: Получить темы
      operationId: getThreads
      tags:
        - Thread
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Thread'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Создать тему
      operationId: createThread
      tags:
        - Thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThread'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thread'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /threads/{id}:
    get:
      summary: Получить тему
      operationId: getThread
      tags:
        - Thread
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thread'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Обновить тему
      operationId: updateThread
      tags:
        - Thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThread'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thread'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Удалить тему
      operationId: deleteThread
      tags:
        - Thread
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /thread-titles:
    get:
      summary: Получить заголовки тем
      operationId: getThreadTitles
      tags:
        - ThreadTitle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThreadTitle'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Создать заголовок темы
      operationId: createThreadTitle
      tags:
        - ThreadTitle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThreadTitle'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadTitle'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /thread-titles/{id}:
    get:
      summary: Получить заголовок темы
      operationId: getThreadTitle
      tags:
        - ThreadTitle
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadTitle'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Обновить заголовок темы
      operationId: updateThreadTitle
      tags:
        - ThreadTitle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThreadTitle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadTitle'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Удалить заголовок темы
      operationId: deleteThreadTitle
      tags:
        - ThreadTitle
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /messages:
    get:
      summary: Получить сообщения
      operationId: getMessages
      tags:
        - Message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Создать сообщение
      operationId: createMessage
      tags:
        - Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessage'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /messages/{id}:
    get:
      summary: Получить сообщение
      operationId: getMessage
      tags:
        - Message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Обновить сообщение
      operationId: updateMessage
      tags:
        - Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessage'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Удалить сообщение
      operationId: deleteMessage
      tags:
        - Message
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /authors:
    get:
      summary: Получить авторов
      operationId: getAuthors
      tags:
        - Author
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Создать автора
      operationId: createAuthor
      tags:
        - Author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /authors/{id}:
    get:
      summary: Получить автора
      operationId: getAuthor
      tags:
        - Author
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Обновить автора
      operationId: updateAuthor
      tags:
        - Author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Удалить автора
      operationId: deleteAuthor
      tags:
        - Author
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Community:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
    ErrorPayload:
      type: object
      properties:
        message:
          type: string
    CreateCommunity:
      type: object
      properties:
        title:
          type: string
    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        avatar:
          type: string
          format: uri
    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        author:
          $ref: '#/components/schemas/Author'
        text:
          type: string
        timestamp:
          type: string
          format: date-time
        reply_to:
          type: string
          format: uuid
    Thread:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        messages_count:
          type: integer
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
    CreateThread:
      type: object
      properties:
        title:
          type: string
    ThreadTitle:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        messages_count:
          type: integer
    CreateThreadTitle:
      type: object
      properties:
        title:
          type: string
    CreateMessage:
      type: object
      properties:
        text:
          type: string
        reply_to:
          type: string
          format: uuid
    CreateAuthor:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
          format: uri
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorPayload'
